codecov:
  require_ci_to_pass: yes
  branch: develop

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        target: 80
        threshold: 2%
        base: auto
        flags:
          - unit
        paths:
          - "src"
        # advanced settings
        branches:
          - master
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
